<a href="https://colab.research.google.com/github/Prince-30502/DSVLab/blob/main/Lec_14_Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

from pandas import Series,DataFrame
import pandas as pd

In [ ]:
#Lets create a Series (array of data and data labels, its index)

obj = Series([3,6,9,12])

#Show
obj

0     3
1     6
2     9
3    12
dtype: int64

In [ ]:
#Lets show the values
obj.values

array([ 3,  6,  9, 12])

In [ ]:
#Lets show the index
obj.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
#Now lets create a Series with an index

#WW2 casualties
ww2_cas = Series([8700000,4300000,3000000,2100000,400000],index=['USSR','Germany','China','Japan','USA'])

#Show
ww2_cas

USSR       8700000
Germany    4300000
China      3000000
Japan      2100000
USA         400000
dtype: int64

In [ ]:
list1 =  (['Hindi','Math','che','phy','Eng'])
list2 =  ([80,50,70,80,90])

marks=Series(list2,list1)
print(marks)

Hindi    80
Math     50
che      70
phy      80
Eng      90
dtype: int64

In [ ]:
#Now we can use index values to select Series values
ww2_cas['USA']

np.int64(400000)

In [ ]:
ww2_cas.loc['USA']

np.int64(400000)

In [ ]:
ww2_cas.index

Index(['USSR', 'Germany', 'China', 'Japan', 'USA'], dtype='object')

In [ ]:
ww2_cas.values

array([8700000, 4300000, 3000000, 2100000,  400000])

In [ ]:
#Can also check with array operations

#Check who had casualties greater than 4 million
ww2_cas[ww2_cas>4000000]

USSR       8700000
Germany    4300000
dtype: int64

In [ ]:
#Can treat Series as ordered dictionary

#Check if USSR is in Series
'USSR' in ww2_cas

True

In [ ]:
#Can convert Series into Python dictionary
ww2_dict = ww2_cas.to_dict()

#Show
ww2_dict

{'USSR': 8700000,
 'Germany': 4300000,
 'China': 3000000,
 'Japan': 2100000,
 'USA': 400000}

In [ ]:
#Can convert back into a Series
WW2_Series = Series(ww2_dict)

In [ ]:
#Show
WW2_Series

USSR       8700000
Germany    4300000
China      3000000
Japan      2100000
USA         400000
dtype: int64

In [ ]:
#Passing a dictionary the index will have the dict keys in order
countries = ['China','Germany','Japan','USA','USSR','Argentina']

In [ ]:
#Lets redefine a Series
obj2 = Series(ww2_dict,index=countries)

In [ ]:
#Show
obj2

China        3000000.0
Germany      4300000.0
Japan        2100000.0
USA           400000.0
USSR         8700000.0
Argentina          NaN
dtype: float64

In [ ]:
#We can use isnull and notnull to find missing data
pd.isnull(obj2)

#obj2.isnull()

China        False
Germany      False
Japan        False
USA          False
USSR         False
Argentina     True
dtype: bool

In [ ]:
#Same for the opposite
pd.notnull(obj2)

#obj2.notnull()

China         True
Germany       True
Japan         True
USA           True
USSR          True
Argentina    False
dtype: bool

In [ ]:
#Lets see the ww2 Series again
WW2_Series

USSR       8700000
Germany    4300000
China      3000000
Japan      2100000
USA         400000
dtype: int64

In [ ]:
#Lets check our Series with Argentine again
obj2

China        3000000.0
Germany      4300000.0
Japan        2100000.0
USA           400000.0
USSR         8700000.0
Argentina          NaN
dtype: float64

In [ ]:
#Now we can add and pandas automatically aligns data by index
WW2_Series + obj2

Argentina           NaN
China         6000000.0
Germany       8600000.0
Japan         4200000.0
USA            800000.0
USSR         17400000.0
dtype: float64

In [ ]:
#We can give Series names
obj2.name = "World War 2 Casualties"

In [ ]:
#Show
obj2

China        3000000.0
Germany      4300000.0
Japan        2100000.0
USA           400000.0
USSR         8700000.0
Argentina          NaN
Name: World War 2 Casualties, dtype: float64

In [ ]:
#We can also name index
obj2.index.name = 'Countries'

In [ ]:
#Show
obj2

Countries
China        3000000.0
Germany      4300000.0
Japan        2100000.0
USA           400000.0
USSR         8700000.0
Argentina          NaN
Name: World War 2 Casualties, dtype: float64